Revert "composer apdate"
This reverts commit ffa103347f1cdb6f80d60e2e3ab613dd57b45065.

diff --git a/vendor/heroku/heroku-buildpack-php/support/build/extensions/no-debug-non-zts-20121212/cassandra b/vendor/heroku/heroku-buildpack-php/support/build/extensions/no-debug-non-zts-20121212/cassandra
--- a/vendor/heroku/heroku-buildpack-php/support/build/extensions/no-debug-non-zts-20121212/cassandra
+++ b/vendor/heroku/heroku-buildpack-php/support/build/extensions/no-debug-non-zts-20121212/cassandra
@@ -1,28 +1,41 @@
 #!/usr/bin/env bash
+# Build Path: /app/.heroku/php/
 
-# we need libgmp-dev
-needed=( libgmp-dev )
-missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
-if [[ "$missing" ]]; then
-	apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-	apt-get install -q -y $missing
-fi
+# fail hard
+set -o pipefail
+# fail harder
+set -eu
 
-dep_name=$(basename $BASH_SOURCE)
+source $(dirname $BASH_SOURCE)/../../_util/include/manifest.sh
 
 OUT_PREFIX=$1
-export PATH=${OUT_PREFIX}/bin:${PATH}
 
-# we need to declare the required version of libcassandra
+ZEND_MODULE_API_VERSION=$(basename $(dirname $0))
+ZEND_MODULE_API_VERSION=${ZEND_MODULE_API_VERSION#no-debug-non-zts-}
+
 dep_formula=${0#$WORKSPACE_DIR/}
+dep_name=$(basename $BASH_SOURCE)
 dep_version=${dep_formula##*"/${dep_name}-"}
-series=$(php-config --version | cut -d. -f1,2) # get "5.5", "5.6", "7.0" etc for the php requirement in the manifest
-case "$dep_version" in
-	*)
-		MANIFEST_REQUIRE="${MANIFEST_REQUIRE:-"{\"heroku-sys/php\":\"${series}.*\",\"heroku-sys/libcassandra\":\"^2.7.0\",\"heroku-sys/libcassandra-abi\":\"^2\"}"}"
+dep_package=ext-${dep_name}-${dep_version}
+case ${ZEND_MODULE_API_VERSION} in
+	20121212)
+		series=5.5
 		;;
+	20131226)
+		series=5.6
+		;;
+	*)
+		series=7.0
 esac
+dep_manifest=${dep_package}_php-$series.composer.json
 
-CONFIGURE_EXTRA="--with-cassandra=${OUT_PREFIX}"
+echo "-----> Merging dependencies..."
 
-source $(dirname $BASH_SOURCE)/../pecl
+MANIFEST_REQUIRE="${MANIFEST_REQUIRE:-"{\"heroku-sys/php\":\"${series}.*\"}"}"
+MANIFEST_CONFLICT="${MANIFEST_CONFLICT:-"{\"heroku-sys/hhvm\":\"*\"}"}"
+MANIFEST_EXTRA="${MANIFEST_EXTRA:-"{}"}"
+MANIFEST_REPLACE="${MANIFEST_REPLACE:-"{}"}"
+
+python $(dirname $BASH_SOURCE)/../../_util/include/manifest.py "heroku-sys-php-extension" "heroku-sys/ext-${dep_name}" "$dep_version" "${dep_formula}.tar.gz" "$MANIFEST_REQUIRE" "$MANIFEST_CONFLICT" "$MANIFEST_REPLACE" "$MANIFEST_EXTRA" > $dep_manifest
+
+print_or_export_manifest_cmd "$(generate_manifest_cmd "$dep_manifest")"
